id = "dayu-themes"
name = "Dayu Themes"
version = "0.0.1"
schema_version = 1
authors = ["dshaw0004 <dipankar@dshaw.dev>"]
description = "Transparent black theme. Name is inspired from Ayu."
repository = "https://github.com/dshaw0004/dayu.git
